### ISSUE TITLE
Transition from "trailservice" to "decide.hypha" contract

### ISSUE THREAD

**Issue by mgravitt** [hypha-dao/eosio-contracts#12]
This will save us some in fees.

**Comment by mgravitt** [comment]
### Steps to implement

1. Create a new account for ```decide.hypha```
2. Deploy ```telos.decide``` contract to ```decide.hypha```
  2.1  Add "surgery" action to allow import of a ballot to a specific state
3. Create the HVOICE token on the ```decide.hypha``` contract
4. Pause the ```dao.hypha``` contract, which will prevent any new ballots from being created
5. Add an RED alert to UI to warn people not to vote (we can't prevent it)
6. Take a snapshot of everyone's HVOICE balance
7.  Mint new HVOICE to all members
8.  Create all open ballots on ```decide.hypha```  (using "surgery" action)
    8.1  Remove "surgery" action and redeploy contract
9. Update all references of ```trailservice``` to ```decide.hypha```
    9.1  Set ```decide.hypha``` to multisig
10. Remove RED alert
11.  Unpause the contract

**Comment by sceenius** [comment]
Note to self: Post alert message 3 days before we do this. 

"The DHO is undergoing some development work on XXXX for about YYY hours and will not be available for transactions"
