### ISSUE TITLE
DHO Badge Payment Calculations

### ISSUE THREAD

**Issue by mgravitt** [hypha-dao/eosio-contracts#21]
DHO badges have multipliers that impact payments.  

Put together a Google Sheet that illustrates test cases for how multiple badges will be stacked together.  Gain alignment on calculations.

## Questions
1. For contributions, will the badge coefficients be applied when proposals are created or when they are paid?  @sceenius 

## Code Updates

- for assignment pay, this needs to be added to the ```payassign``` action
- for contributions, see open question

**Comment by sceenius** [comment]
I think either "paid" or "proposal passed & activated", maybe "paid" since this is more aligned with "claimed" (For assignments)
