### ISSUE TITLE
Native ballots for voting activities

### ISSUE THREAD

**Issue by mgravitt** [hypha-dao/eosio-contracts#26]
There are 2 overarching goals for this feature:
1. Replace telos.decide to eliminate fees and RAM troubles for members
2. Add vote tallies to the document graph

Here's what I'm thinking for the graph structure:

![image](https://user-images.githubusercontent.com/32852271/96378277-d39ce080-1158-11eb-8beb-f1f5a47625ad.png)

And the sequence of events would occur like this: 
![image](https://user-images.githubusercontent.com/32852271/96378557-bcf78900-115a-11eb-8ec0-fba99704b183.png)

**Comment by mgravitt** [comment]
In addition to simple pass/fail proposals, we also should support custom choices.  The voter may choose 1-n options from a list and optionally place weights on each option.  

The proposal document will maintain configuration data about the options, and the vote and tally documents will maintain data on the selected options/weights for the specific vote and in total.

Are there any other proposal/ballot/voting types that should be supported in this phase?
@sceenius

**Comment by mgravitt** [comment]
## Potential Tally Document
``` json
{                                                                                                          
    "creator": "dao.hypha",    
    "content_groups": [
        [
            {
                "label": "vote_power",
                "value": [
                    "asset",
                    "12000.00 HVOICE"
                ]
            },
            {
                "label": "fail",
                "value": [
                    "string",
                    "fail"
                ]
            }        
        ],
        [
            {
                "label": "vote_power",
                "value": [
                    "asset",
                    "15000.00 HVOICE"
                ]
            },
            {
                "label": "pass",
                "value": [
                    "string",
                    "pass"
                ]
            }        
        ]
    ]
}
```

## Potential Vote Document
``` json
{                                                                                                          
    "creator": "johnnyhypha1",     // aka voter
    "content_groups": [
        [
            {
                "label": "vote_power",
                "value": [
                    "asset",
                    "12000.00 HVOICE"
                ]
            },
            {
                "label": "fail",
                "value": [
                    "string",
                    "fail"
                ]
            }        
        ]
    ]
}
```

**Comment by sebastianmontero** [comment]
It looks good to me, I don't think the certificate is necessary, if you are voting on the proposal it means you are in agreement with it.

**Comment by mgravitt** [comment]
The hope here is that we will have both telos.decide and non-telos.decide operational at the same time to allow for a running change.  To enable this, 

- [ ] ```propose``` action will create new style proposal IF ballot_type is set to ```options``` (ballot_type will default to ```telosdecide``` if not provided) 
- [ ] deploy a new token contract for HVOICE (non-transferable token)
- [ ] update ```enroll``` to mint a TD HVOICE and a non TD HVOICE
- [ ] add the ```vote``` action to the dao contract

```
ACTION hyphadao::vote (const name &voter, const checksum &proposal, const vector<content_group> vote)
```
This action will: 
1. create the document
2. add an edge from the member to the vote named ```vote```
3. add an edge from the proposal to the vote named ```vote```
4. an edge from the vote to the member named ```ownedby```
5. an edge from the vote to the proposal named ```voteon```

- [ ] update bank to mint both version of HVOICE
