### ISSUE TITLE
Support for point-in-time SEEDS price calculation

### ISSUE THREAD

**Issue by mgravitt** [hypha-dao/eosio-contracts#6]
Currently, the SEEDS price is pulled from the tlosto.seeds contract when an object is proposed or edited. This is used to translate USD amounts into SEEDS.

This should change such that the price is pulled as of the start date of the period (moon phase-not moon cycle) being claimed. 

However, for contributions, we do not want proposals to be able to go 'way back' into history or selectively choose their contribution date based on the SEEDS price.  To control for this, we will always take the maximum of the object's created date and the start date.

Technical notes: 
- write function to pass a date as input and return the SEEDS price based on the data in the tlosto.seeds::pricehistory table: https://telos.bloks.io/account/tlosto.seeds?loadContract=true&tab=Tables&account=tlosto.seeds&scope=tlosto.seeds&limit=100&table=pricehistory

- update ```payassign``` action to dynamically call above function to calculate the SEEDS quantity rather than pulling the SEEDS quantity from the assignment

- remove the SEEDS quantities from the assignment records

- ensure that the ```usd_amount``` of the role is saved with the assignment when it is created 

- TBD - evaluate making this same change for the other tokens as well

**Comment by sceenius** [comment]
![image](https://user-images.githubusercontent.com/24725582/91480716-61530280-e871-11ea-821e-77b63bee938c.png)

**Comment by mgravitt** [comment]
I will be copying the ```usd_amount``` from the role to the assignment when the assignment is created. This means that edits to a role will NOT be apply to existing assignments. We have to choose one or the other and this seems to be most appropriate.

**Comment by sceenius** [comment]
Let's discuss the connection between role and assignment again later. Role
is suspended/edited/created >>> implications for assignments.

**Comment by mgravitt** [comment]
Here are the integration test results on the testnet:

The price change was made on 08/25.  This was during Period 56, also seen in the screen shot. We should see a higher amount paid for Period 55 than we do for Period 56.  (the calculations themselves can be verified on the Google Sheet)

<img width="746" alt="image" src="https://user-images.githubusercontent.com/32852271/92413129-a2260380-f11c-11ea-857d-fc69f2742109.png">

Here you can see that I call ```payassign``` (the action that claims pay) on both period 55 and 56, and then I print the debug log to show the difference in the DEFERRED SEEDS quantities:

(NOTE that the debug log is printed in reverse order so it actually shows period 56 first, and then period 55.)

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/32852271/92413234-211b3c00-f11d-11ea-84e2-3ddd09109b49.png">

**Comment by mgravitt** [comment]
NOTE: Contributions also have start and end periods as inputs, so I use the SEEDS price **at the end period input** to calculate the escrow amount.

**Comment by mgravitt** [comment]
Here's the similar view on Contribution proposals.  The top one is with a lower price, and second one is higher.  

<img width="853" alt="image" src="https://user-images.githubusercontent.com/32852271/92417106-8f1c2f00-f12e-11ea-9687-6147623fcd0d.png">

**Comment by mgravitt** [comment]
@sceenius if you approve, I can deploy this to prod

**Comment by sceenius** [comment]
Great, this looks good.
